#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EasyFTF.Resource", IsApplication=true)]

namespace EasyFTF
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int common_action_bar_splitter = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int common_google_signin_btn_text_dark = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_dark_default = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_dark_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_signin_btn_text_dark_focused = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark_pressed = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int common_google_signin_btn_text_light = 2131099666;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_signin_btn_text_light_default = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_light_disabled = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light_focused = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_signin_btn_text_light_pressed = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int common_plus_signin_btn_text_dark = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int common_plus_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_plus_signin_btn_text_dark_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_plus_signin_btn_text_dark_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_plus_signin_btn_text_dark_pressed = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int common_plus_signin_btn_text_light = 2131099668;
			
			// aapt resource value: 0x7f060004
			public const int common_plus_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_plus_signin_btn_text_light_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_plus_signin_btn_text_light_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_plus_signin_btn_text_light_pressed = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bulletgreen = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bulletred = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cancel = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int @checked = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CITO = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_full_open_on_phone = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_disabled = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark_focused = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_dark_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_dark_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_disabled = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light_focused = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_light_normal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_icon_light_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_disabled = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark_focused = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_dark_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_dark_pressed = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_text_light_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_text_light_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_ic_googleplayservices = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_dark_focused = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_dark_normal = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_icon_light_disabled = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_icon_light_focused = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_icon_light_normal = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_icon_light_pressed = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_dark_disabled = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_dark_focused = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_dark_normal = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_dark_pressed = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_text_light_disabled = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_plus_signin_btn_text_light_focused = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_plus_signin_btn_text_light_normal = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_plus_signin_btn_text_light_pressed = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int configure = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int coordinate = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int create = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int debug = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Earth = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int email = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Event = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Giga = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Icon = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int latlon = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Letterbox = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int login = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int map = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int Mega = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int Multi = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int name = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int password = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int quit = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int radius = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int save = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int selection = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int splash_logo = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int Tradi = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int types = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int @unchecked = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int Unknown = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int Unsupported = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int update = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int Virtual = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int Wherigo = 2130837581;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09003b
			public const int About = 2131296315;
			
			// aapt resource value: 0x7f090038
			public const int Add = 2131296312;
			
			// aapt resource value: 0x7f09002f
			public const int BtnQuit = 2131296303;
			
			// aapt resource value: 0x7f09001a
			public const int Cancel = 2131296282;
			
			// aapt resource value: 0x7f09003a
			public const int Configure = 2131296314;
			
			// aapt resource value: 0x7f090039
			public const int MenuSel = 2131296313;
			
			// aapt resource value: 0x7f090023
			public const int PickMap = 2131296291;
			
			// aapt resource value: 0x7f09003c
			public const int Quit = 2131296316;
			
			// aapt resource value: 0x7f09001b
			public const int Save = 2131296283;
			
			// aapt resource value: 0x7f090037
			public const int Update = 2131296311;
			
			// aapt resource value: 0x7f09002e
			public const int UpdateEmails = 2131296302;
			
			// aapt resource value: 0x7f09000e
			public const int aboutDbg = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int aboutImg = 2131296269;
			
			// aapt resource value: 0x7f090005
			public const int adjust_height = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int adjust_width = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int auto = 2131296266;
			
			// aapt resource value: 0x7f090022
			public const int btnCoord = 2131296290;
			
			// aapt resource value: 0x7f090031
			public const int custom_marker_popup_snippet = 2131296305;
			
			// aapt resource value: 0x7f090030
			public const int custom_marker_popup_title = 2131296304;
			
			// aapt resource value: 0x7f09000b
			public const int dark = 2131296267;
			
			// aapt resource value: 0x7f090021
			public const int editCoord = 2131296289;
			
			// aapt resource value: 0x7f090016
			public const int editLogin = 2131296278;
			
			// aapt resource value: 0x7f09001e
			public const int editName = 2131296286;
			
			// aapt resource value: 0x7f090019
			public const int editPassword = 2131296281;
			
			// aapt resource value: 0x7f09002a
			public const int editRadius = 2131296298;
			
			// aapt resource value: 0x7f090027
			public const int gridview = 2131296295;
			
			// aapt resource value: 0x7f090000
			public const int hybrid = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int icon_only = 2131296263;
			
			// aapt resource value: 0x7f09002b
			public const int imageEmail = 2131296299;
			
			// aapt resource value: 0x7f09001f
			public const int imageLatlon = 2131296287;
			
			// aapt resource value: 0x7f090014
			public const int imageLogin = 2131296276;
			
			// aapt resource value: 0x7f09001c
			public const int imageName = 2131296284;
			
			// aapt resource value: 0x7f090017
			public const int imagePassword = 2131296279;
			
			// aapt resource value: 0x7f090028
			public const int imageRadius = 2131296296;
			
			// aapt resource value: 0x7f090025
			public const int imageTypes = 2131296293;
			
			// aapt resource value: 0x7f090033
			public const int imageView_icon = 2131296307;
			
			// aapt resource value: 0x7f090032
			public const int imageView_prefix = 2131296306;
			
			// aapt resource value: 0x7f09000f
			public const int lblAbout = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int lblAboutMail = 2131296272;
			
			// aapt resource value: 0x7f090036
			public const int lblAccountInfo = 2131296310;
			
			// aapt resource value: 0x7f090020
			public const int lblCoord = 2131296288;
			
			// aapt resource value: 0x7f090024
			public const int lblCoordAllValues = 2131296292;
			
			// aapt resource value: 0x7f09002c
			public const int lblEmail = 2131296300;
			
			// aapt resource value: 0x7f090011
			public const int lblHelp = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int lblLicense = 2131296274;
			
			// aapt resource value: 0x7f090015
			public const int lblLogin = 2131296277;
			
			// aapt resource value: 0x7f090013
			public const int lblMaps = 2131296275;
			
			// aapt resource value: 0x7f09001d
			public const int lblName = 2131296285;
			
			// aapt resource value: 0x7f090018
			public const int lblPassword = 2131296280;
			
			// aapt resource value: 0x7f090029
			public const int lblRadius = 2131296297;
			
			// aapt resource value: 0x7f090026
			public const int lblTypes = 2131296294;
			
			// aapt resource value: 0x7f09000c
			public const int light = 2131296268;
			
			// aapt resource value: 0x7f09003d
			public const int lvItems = 2131296317;
			
			// aapt resource value: 0x7f09003e
			public const int map = 2131296318;
			
			// aapt resource value: 0x7f090048
			public const int menu_delete = 2131296328;
			
			// aapt resource value: 0x7f090044
			public const int menu_deselectall = 2131296324;
			
			// aapt resource value: 0x7f090043
			public const int menu_selectall = 2131296323;
			
			// aapt resource value: 0x7f090047
			public const int menu_showonmap = 2131296327;
			
			// aapt resource value: 0x7f090042
			public const int menu_sort = 2131296322;
			
			// aapt resource value: 0x7f09003f
			public const int menu_sort_age = 2131296319;
			
			// aapt resource value: 0x7f090040
			public const int menu_sort_name = 2131296320;
			
			// aapt resource value: 0x7f090041
			public const int menu_sort_type = 2131296321;
			
			// aapt resource value: 0x7f090045
			public const int menu_toggle = 2131296325;
			
			// aapt resource value: 0x7f090046
			public const int menu_update = 2131296326;
			
			// aapt resource value: 0x7f090001
			public const int none = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int normal = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int satellite = 2131296259;
			
			// aapt resource value: 0x7f09002d
			public const int spinnerEmail = 2131296301;
			
			// aapt resource value: 0x7f090008
			public const int standard = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int terrain = 2131296260;
			
			// aapt resource value: 0x7f090035
			public const int textView_Info = 2131296309;
			
			// aapt resource value: 0x7f090034
			public const int textView_Name = 2131296308;
			
			// aapt resource value: 0x7f090009
			public const int wide = 2131296265;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Configuration = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Creation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CustomMarkerPopup = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int list_item_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int list_item_layout2 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MapLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ShowOnMapLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int UpdateCoordLayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int sort_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int top_menus = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040022
			public const int About = 2130968610;
			
			// aapt resource value: 0x7f04001f
			public const int AccountConfigure = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int AccountError = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int AccountGood = 2130968609;
			
			// aapt resource value: 0x7f040023
			public const int Add = 2130968611;
			
			// aapt resource value: 0x7f040027
			public const int ApplicationName = 2130968615;
			
			// aapt resource value: 0x7f04002a
			public const int BadCoordinates = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int BadDistance = 2130968619;
			
			// aapt resource value: 0x7f04002f
			public const int BadEmail = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int BadName = 2130968624;
			
			// aapt resource value: 0x7f04002d
			public const int BtnCreate = 2130968621;
			
			// aapt resource value: 0x7f04002c
			public const int BtnModify = 2130968620;
			
			// aapt resource value: 0x7f040031
			public const int BtnNo = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int BtnOK = 2130968626;
			
			// aapt resource value: 0x7f04002e
			public const int BtnPick = 2130968622;
			
			// aapt resource value: 0x7f040033
			public const int BtnQuit = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int BtnYes = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int Cancel = 2130968629;
			
			// aapt resource value: 0x7f040068
			public const int Canceled = 2130968680;
			
			// aapt resource value: 0x7f040036
			public const int Configure = 2130968630;
			
			// aapt resource value: 0x7f04003b
			public const int ConfirmCancelCreate = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int ConfirmCancelPick = 2130968636;
			
			// aapt resource value: 0x7f040039
			public const int ConfirmCancelUpdateCoord = 2130968633;
			
			// aapt resource value: 0x7f04003e
			public const int ConfirmCreate = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int ConfirmDelete = 2130968639;
			
			// aapt resource value: 0x7f040038
			public const int ConfirmGoBack = 2130968632;
			
			// aapt resource value: 0x7f04003d
			public const int ConfirmPick = 2130968637;
			
			// aapt resource value: 0x7f040040
			public const int ConfirmToggle = 2130968640;
			
			// aapt resource value: 0x7f04003a
			public const int ConfirmUpdateCoord = 2130968634;
			
			// aapt resource value: 0x7f040041
			public const int Coordinates = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int Delete = 2130968642;
			
			// aapt resource value: 0x7f04006e
			public const int DeselectAll = 2130968686;
			
			// aapt resource value: 0x7f040043
			public const int Email = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int Error = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int ErrorLocation = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int ErrorNoGPSFix = 2130968646;
			
			// aapt resource value: 0x7f040048
			public const int ExpireDate = 2130968648;
			
			// aapt resource value: 0x7f040077
			public const int ExpiredVersion = 2130968695;
			
			// aapt resource value: 0x7f040047
			public const int Full = 2130968647;
			
			// aapt resource value: 0x7f04004a
			public const int GPSFix = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int GPSFixSet = 2130968651;
			
			// aapt resource value: 0x7f040049
			public const int GetGPS = 2130968649;
			
			// aapt resource value: 0x7f040037
			public const int GoBack = 2130968631;
			
			// aapt resource value: 0x7f04004d
			public const int LblAccountVerif = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int LblCreateInProgress = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int LblDeleteInProgress = 2130968655;
			
			// aapt resource value: 0x7f040053
			public const int LblDisplayInProgress = 2130968659;
			
			// aapt resource value: 0x7f04004c
			public const int LblEmailInProgress = 2130968652;
			
			// aapt resource value: 0x7f040050
			public const int LblInitInProgress = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int LblToggleInProgress = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int LblUpdateInProgress = 2130968658;
			
			// aapt resource value: 0x7f040025
			public const int License = 2130968613;
			
			// aapt resource value: 0x7f040054
			public const int Lite = 2130968660;
			
			// aapt resource value: 0x7f040055
			public const int Login = 2130968661;
			
			// aapt resource value: 0x7f040024
			public const int Mail = 2130968612;
			
			// aapt resource value: 0x7f040028
			public const int MaxNotifReached = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int MaxNotifWillReached = 2130968617;
			
			// aapt resource value: 0x7f040071
			public const int MergedMarkers = 2130968689;
			
			// aapt resource value: 0x7f040056
			public const int Name = 2130968662;
			
			// aapt resource value: 0x7f040057
			public const int NoEmailGC = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int NoInternet = 2130968664;
			
			// aapt resource value: 0x7f040059
			public const int NoNotif = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int NoPremium = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int NoType = 2130968667;
			
			// aapt resource value: 0x7f040075
			public const int OnlyFullMap = 2130968693;
			
			// aapt resource value: 0x7f040072
			public const int OnlyFullNotif = 2130968690;
			
			// aapt resource value: 0x7f040074
			public const int OnlyFullShowOnMap = 2130968692;
			
			// aapt resource value: 0x7f040076
			public const int OnlyFullTypes = 2130968694;
			
			// aapt resource value: 0x7f040073
			public const int OnlyFullUpdateCoord = 2130968691;
			
			// aapt resource value: 0x7f04005c
			public const int OperationInProgress = 2130968668;
			
			// aapt resource value: 0x7f04005d
			public const int Password = 2130968669;
			
			// aapt resource value: 0x7f04005f
			public const int PickDone = 2130968671;
			
			// aapt resource value: 0x7f04005e
			public const int PickMap = 2130968670;
			
			// aapt resource value: 0x7f040060
			public const int Quit = 2130968672;
			
			// aapt resource value: 0x7f040061
			public const int QuitMsg = 2130968673;
			
			// aapt resource value: 0x7f040062
			public const int Radius = 2130968674;
			
			// aapt resource value: 0x7f040063
			public const int Save = 2130968675;
			
			// aapt resource value: 0x7f04006d
			public const int SelectAll = 2130968685;
			
			// aapt resource value: 0x7f040026
			public const int ShowHelp = 2130968614;
			
			// aapt resource value: 0x7f04006f
			public const int ShowMap = 2130968687;
			
			// aapt resource value: 0x7f040064
			public const int SortList = 2130968676;
			
			// aapt resource value: 0x7f040065
			public const int SortListAge = 2130968677;
			
			// aapt resource value: 0x7f040066
			public const int SortListName = 2130968678;
			
			// aapt resource value: 0x7f040067
			public const int SortListType = 2130968679;
			
			// aapt resource value: 0x7f040069
			public const int Success = 2130968681;
			
			// aapt resource value: 0x7f04006a
			public const int Toggle = 2130968682;
			
			// aapt resource value: 0x7f04006b
			public const int Types = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int Update = 2130968684;
			
			// aapt resource value: 0x7f040070
			public const int UpdateCoord = 2130968688;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_api_unavailable_text = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_enable_text = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_enable_title = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_button = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_text_phone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_text_tablet = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_install_title = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_invalid_account_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_invalid_account_title = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_network_error_text = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_network_error_title = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_ticker = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_play_services_restricted_profile_text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_restricted_profile_title = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_sign_in_failed_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_sign_in_failed_title = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_unsupported_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_unsupported_title = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_update_button = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_title = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_updating_text = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_updating_title = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_wear_update_text = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int common_signin_button_text_long = 2130968606;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
